/*
 * File: app/controller/BaseController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.controller.BaseController', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'BaseController'
    ],
    requires: [
        'Ext.window.Toast'
    ],

    refs: {
        mainTabPanel: {
            selector: 'viewport #mainTabPanel',
            xtype: 'Ext.tab.Panel'
        }
    },

    showSuccessMessage: function(title) {
        debugger;
        var t = Ext.toast({
            html: 'İşlem Başarılı',
            width: 300,
            //hideDuration: 1000,
            //autoCloseDelay: 1000,
            ariaRole: 'alert',
            header: true,
            title: title,
            closable:true,
            animate: true,
            slideInAnimation: 'ease',
            align: 't',
            cls:'showSuccessMessage',
            style: 'border: 0px;border-radius: 10px; webkit-border-radius: 10px; -moz-border-radius: 10px;'
        });
        t.show();
    },

    showErrorMessage: function(message) {
        debugger;
        var t = Ext.toast({
            html: message,
            width: 300,
            hideDuration: 3000,
            autoCloseDelay: 3000,
            ariaRole: 'alert',
            header: true,
            title: 'Hata',
            animate: true,
            slideInAnimation: 'ease',
            align: 't',
            cls:'showErrorMessage',
            style: 'border: 0px;border-radius: 10px; webkit-border-radius: 10px; -moz-border-radius: 10px;'
        });
        t.show();
    },

    showWarningMessage: function(message) {
        debugger;
        var t = Ext.toast({
            html: message,
            width: 300,
            hideDuration: 3000,
            autoCloseDelay: 3000,
            ariaRole: 'alert',
            header: true,
            title: 'Uyarı',
            animate: true,
            slideInAnimation: 'ease',
            align: 't',
            cls:'showWarningMessage',
            style: 'border: 0px;border-radius: 10px; webkit-border-radius: 10px; -moz-border-radius: 10px;'
        });
        t.show();
    }

});
