/*
 * File: app/controller/HrController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.controller.HrController', {
    extend: 'BaseController',

    views: [
        'hrSaveOrUpdate'
    ],

    control: {
        "#btnHrSaveOrUpdateWindow": {
            click: 'onBtnHrSaveOrUpdateWindowClick'
        },
        "#hrTabPanel": {
            tabchange: 'onHrTabPanelTabChange'
        },
        "#btnHrSaveOrUpdate": {
            click: 'onBtnHrSaveOrUpdateClick'
        },
        "#hrLeaveGrid": {
            rowclick: 'onHrLeaveGridRowClick'
        },
        "#recordTypeId": {
            change: 'onRecordTypeIdChange'
        },
        "#searchHrGrid": {
            keyup: 'onSearchHrGridKeyup'
        },
        "#searchHrLeaveGrid": {
            keyup: 'onSearchHrLeaveGridKeyup'
        },
        "#btnAddLeaveDetail": {
            click: 'onBtnAddLeaveDetailClick'
        },
        "#leaveDetailGrid": {
            expand: 'onLeaveDetailGridExpand'
        },
        "#btnRemoveLeaveDetail": {
            click: 'onBtnRemoveLeaveDetailClick'
        }
    },

    onBtnHrSaveOrUpdateWindowClick: function(button, e, eOpts) {
        debugger;
        var winHrSaveOrUpdate = Ext.create('byzCorp.view.hrSaveOrUpdate',{
            title: button.text,
            xtype:'panel',
            iconCls:button.iconCls,
            closable: true,
        });
        var scope = this;
        var hrGridSelected = Ext.getCmp("hrGrid").getSelectionModel().getSelection();
        if(hrGridSelected.length==0){
            winHrSaveOrUpdate.show();
        }else{
            winHrSaveOrUpdate.show();
            Ext.getCmp('hrSubInfoWest').getForm().setValues(hrGridSelected[0].data);
            Ext.getCmp('hrSubInfoEast').getForm().setValues(hrGridSelected[0].data);
            Ext.getCmp('hrSubInfoCenter').getForm().setValues(hrGridSelected[0].data);
            Ext.getCmp('hrInfoWest').getForm().setValues(hrGridSelected[0].data);
            Ext.getCmp('hrInfoEast').getForm().setValues(hrGridSelected[0].data);
            Ext.getCmp('hrInfoCenter').getForm().setValues(hrGridSelected[0].data);
           }
    },

    onHrTabPanelTabChange: function(tabPanel, newCard, oldCard, eOpts) {
        debugger;
        var userId = Ext.getCmp('userId').getValue();
        if(userId==""){
          userId = Ext.getCmp('hrGrid').getSelectionModel().getSelected().items[0].data.userId;
        }
        if((tabPanel.getActiveTab().getId()!='hrInfo')){
        Ext.getCmp(tabPanel.getActiveTab().getId()+'Grid').getStore().load({
            params:{
                userId : userId
            }
        });
        if((tabPanel.getActiveTab().getId()!='hrLeave')){
            Ext.getCmp('leaveDetailGrid').getStore().load({
                    params:{
                        userId : userId
                    }
            });
        }
        }
    },

    onBtnHrSaveOrUpdateClick: function(button, e, eOpts) {
        var scope = this;
        var activeTabId = Ext.getCmp('hrTabPanel').getActiveTab().id;
        debugger;
        if(activeTabId=='hrInfo'){
            Ext.Ajax.request({
            url:'/byzCorp/hr/saveOrUpdateHr',
            params : {
                subInfoWest : Ext.encode(Ext.getCmp('hrSubInfoWest').getForm().getValues()),
                subInfoEast : Ext.encode(Ext.getCmp('hrSubInfoEast').getForm().getValues()),
                subInfoCenter :Ext.encode(Ext.getCmp('hrSubInfoCenter').getForm().getValues()),
                infoWest : Ext.encode(Ext.getCmp('hrInfoWest').getForm().getValues()),
                infoEast : Ext.encode(Ext.getCmp('hrInfoEast').getForm().getValues()),
                infoCenter : Ext.encode(Ext.getCmp('hrInfoCenter').getForm().getValues())
            },
            success : function(response){
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                if(jsonData.success){debugger;
                scope.showSuccessMessage();
                Ext.getCmp("managerId").focus();
                Ext.getCmp('hrGrid').getStore().load();
                }else{
                    scope.showErrorMessage(jsonData.message);
                    Ext.getCmp("managerId").focus();
                }
            },
            failure: function (response) {
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                scope.showErrorMessage(jsonData.message);
                Ext.getCmp("managerId").focus();
            }
        });
        }else if(activeTabId=='hrLeave'){
            Ext.Ajax.request({
            url:'/byzCorp/hr/saveOrUpdateHrLeave',
            params : {
                subInfoWest : Ext.encode(Ext.getCmp('hrSubInfoWest').getForm().getValues()),
                subInfoEast : Ext.encode(Ext.getCmp('hrSubInfoEast').getForm().getValues()),
                subInfoCenter :Ext.encode(Ext.getCmp('hrSubInfoCenter').getForm().getValues()),
                hrLeave : Ext.encode(Ext.getCmp('leaveSaveOrUpdateForm').getForm().getValues())
            },
            success : function(response){
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                if(jsonData.success){debugger;
                scope.showSuccessMessage();
                Ext.getCmp("reportTypeId").focus();
                Ext.getCmp('hrGrid').getStore().load();
                Ext.getCmp('hrLeaveGrid').getStore().load();
                Ext.getCmp("leaveSaveOrUpdateForm").getForm().reset();
                }else{
                    scope.showErrorMessage(jsonData.message);
                    Ext.getCmp("reportTypeId").focus();
                }
            },
            failure: function (response) {
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                scope.showErrorMessage(jsonData.message);
                Ext.getCmp("reportTypeId").focus();
            }
        });
        }

    },

    onHrLeaveGridRowClick: function(tableview, record, element, rowIndex, e, eOpts) {
        debugger;
        if(record.data.recordTypeId==1){
            Ext.getCmp("reportTypeId").setVisible(false);
            Ext.getCmp("leaveTypeId").setVisible(true);
            Ext.getCmp("leaveYear").setVisible(true);
        }else{
            Ext.getCmp("reportTypeId").setVisible(true);
            Ext.getCmp("leaveTypeId").setVisible(false);
            Ext.getCmp("leaveYear").setVisible(false);
        }
        Ext.getCmp("leaveSaveOrUpdateForm").getForm().setValues(record.data);
    },

    onRecordTypeIdChange: function(field, newValue, oldValue, eOpts) {
        debugger;
        if(newValue==1){
            Ext.getCmp("leaveTypeId").setVisible(true);
            Ext.getCmp("leaveYear").setVisible(true);
            Ext.getCmp("reportTypeId").setVisible(false);
        }else{
            Ext.getCmp("leaveTypeId").setVisible(false);
            Ext.getCmp("leaveYear").setVisible(false);
            Ext.getCmp("reportTypeId").setVisible(true);
        }
    },

    onSearchHrGridKeyup: function(textfield, e, eOpts) {
        var query = Ext.getCmp("searchHrGrid").getValue();
        var hrGrid = Ext.getCmp("hrGrid");
        hrGrid.getStore().load({
            params:{
                query : query
            }
        });
    },

    onSearchHrLeaveGridKeyup: function(textfield, e, eOpts) {
        var query = Ext.getCmp("searchHrLeaveGrid").getValue();
                var hrGrid = Ext.getCmp("hrLeaveGrid");
                hrGrid.getStore().load({
                    params:{
                        query : query
                    }
                });
    },

    onBtnAddLeaveDetailClick: function(button, e, eOpts) {
        debugger;
        var scope = this;
        leaveDetailYear = Ext.getCmp('leaveDetailYearId').getValue();
        leaveDetailDay = Ext.getCmp('leaveDetailDay').getValue();
        userId = Ext.getCmp('userId').getValue();
        Ext.Ajax.request({
            url:'/byzCorp/hr/saveOrUpdateHrLeaveDetail',
            params : {
                leaveDetailYear : leaveDetailYear,
                leaveDetailDay : leaveDetailDay,
                userId : userId
            },
            success : function(response){
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                if(jsonData.success){
                scope.showSuccessMessage();
                Ext.getCmp('leaveDetailYearId').focus();
                Ext.getCmp('leaveDetailGrid').getStore().load();
                }else{
                    scope.showErrorMessage(jsonData.message);
                    Ext.getCmp("leaveDetailYearId").focus();
                }
            },
            failure: function (response) {
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                scope.showErrorMessage(jsonData.message);
                Ext.getCmp("leaveDetailYearId").focus();
            }

        });
    },

    onLeaveDetailGridExpand: function(p, eOpts) {
        debugger;
        var userId = Ext.getCmp('userId').getValue();
        Ext.getCmp('leaveDetailGrid').getStore().load({
            params:{
                userId : userId
            }
        });
        /*Ext.getCmp('leaveDetailGrid').getStore().addListener('beforeload', function(store, option){
            option.params_counrtyId = countryId;
        });*/

    },

    onBtnRemoveLeaveDetailClick: function(button, e, eOpts) {
        debugger;
        var scope = this;
        hrLeaveDetailId = Ext.getCmp('leaveDetailGrid').getSelectionModel().getSelected().items[0].data.hrLeaveDetailId;
        if(hrLeaveDetailId==""){
            scope.showWarningMessage("Listeden silmek istediğiniz kaydı seçiniz.");
        }
        Ext.Ajax.request({
            url:'/byzCorp/hr/removeHrLeaveDetail',
            params : {
                hrLeaveDetailId : hrLeaveDetailId
            },
            success : function(response){
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                if(jsonData.success){
                scope.showSuccessMessage('Silme');
                Ext.getCmp('leaveDetailYear').focus();
                Ext.getCmp('leaveDetailGrid').getStore().load();
                }else{
                    scope.showErrorMessage(jsonData.message);
                    Ext.getCmp("leaveDetailYear").focus();
                }
            },
            failure: function (response) {
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                scope.showErrorMessage(jsonData.message);
                Ext.getCmp("leaveDetailYear").focus();
            }

        });
    }

});
