/*
 * File: app/controller/MenuController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.controller.MenuController', {
    extend: 'BaseController',

    id: 'MenuController',

    control: {
        "#menuBtnFinanceManagement": {
            click: 'onMenuBtnFinanceManagementClick'
        },
        "#menuBtnStockManagement": {
            click: 'onMenuBtnStockManagementClick'
        },
        "#menuBtnHrManagement": {
            click: 'onMenuBtnHrManagementClick'
        },
        "#menuBtnOtelManagement": {
            click: 'onMenuBtnOtelManagementClick'
        },
        "#menuBtnLookUpManagement": {
            click: 'onMenuBtnLookUpManagementClick'
        }
    },

    onMenuBtnFinanceManagementClick: function(button, e, eOpts) {
        this.showSuccessMessage();
        this.showErrorMessage('Hata mesajı verildi.');
        this.showWarningMessage('Uyarı mesajı verildi.');
        var mainTabPanel = this.getMainTabPanel();
        var financeTabPanel = mainTabPanel.items.findBy(
        	function (tab){
            	return tab.title === button.text;
            }
        );

        if (!financeTabPanel){
        var financeManagement = Ext.create('byzCorp.view.financeManagement',{
            title: button.text,
            xtype:'panel',
            iconCls:button.iconCls,
            closable: true,
        });
        financeTabPanel = mainTabPanel.add(financeManagement);
        }
        mainTabPanel.setActiveTab(financeTabPanel);
    },

    onMenuBtnStockManagementClick: function(button, e, eOpts) {
        var mainTabPanel = this.getMainTabPanel();
        var stockTabPanel = mainTabPanel.items.findBy(
        	function (tab){
            	return tab.title === button.text;
            }
        );

        if (!stockTabPanel){
        var stockManagement = Ext.create('byzCorp.view.stockManagement',{
            title: button.text,
            xtype:'panel',
            iconCls:button.iconCls,
            closable: true,
        });
        stockTabPanel = mainTabPanel.add(stockManagement);
        }
        mainTabPanel.setActiveTab(stockTabPanel);
    },

    onMenuBtnHrManagementClick: function(button, e, eOpts) {
        var mainTabPanel = this.getMainTabPanel();
        var hrTabPanel = mainTabPanel.items.findBy(
        	function (tab){
            	return tab.title === button.text;
            }
        );

        if (!hrTabPanel){
        var hrManagement = Ext.create('byzCorp.view.hrManagement',{
            title: button.text,
            xtype:'panel',
            iconCls:button.iconCls,
            closable: true,
        });
        hrTabPanel = mainTabPanel.add(hrManagement);
        }
        mainTabPanel.setActiveTab(hrTabPanel);
    },

    onMenuBtnOtelManagementClick: function(button, e, eOpts) {
        var mainTabPanel = this.getMainTabPanel();
        var otelTabPanel = mainTabPanel.items.findBy(
        	function (tab){
            	return tab.title === button.text;
            }
        );

        if (!otelTabPanel){
        var otelManagement = Ext.create('byzCorp.view.otelManagement',{
            title: button.text,
            xtype:'panel',
            iconCls:button.iconCls,
            closable: true,
        });
        otelTabPanel = mainTabPanel.add(otelManagement);
        }
        mainTabPanel.setActiveTab(otelTabPanel);
    },

    onMenuBtnLookUpManagementClick: function(button, e, eOpts) {
        var mainTabPanel = this.getMainTabPanel();
        var lookUpTabPanel = mainTabPanel.items.findBy(
        	function (tab){
            	return tab.title === button.text;
            }
        );

        if (!lookUpTabPanel){
        var lookUpManagement = Ext.create('byzCorp.view.lookUpManagement',{
            title: button.text,
            xtype:'panel',
            iconCls:button.iconCls,
            closable: true,
        });
        lookUpTabPanel = mainTabPanel.add(lookUpManagement);
        }
        mainTabPanel.setActiveTab(lookUpTabPanel);
    }

});
