/*
 * File: app/model/userLeave.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.model.userLeave', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'userLeaveId'
        },
        {
            name: 'userId'
        },
        {
            name: 'recordTypeId'
        },
        {
            name: 'recordTypeName'
        },
        {
            name: 'leaveTypeId'
        },
        {
            name: 'reportTypeId'
        },
        {
            name: 'typeName'
        },
        {
            name: 'startDate'
        },
        {
            name: 'endDate'
        },
        {
            name: 'leaveStartWorkDate'
        },
        {
            name: 'time'
        },
        {
            name: 'leaveYear'
        },
        {
            name: 'leaveStatus'
        }
    ]
});