/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.controller.LoginController', {
    extend: 'BaseController',

    id: 'LoginController',

    control: {
        "#btnLogin": {
            click: 'onBtnLoginClick'
        }
    },

    onBtnLoginClick: function(button, e, eOpts) {
        var scope = this;
        Ext.Ajax.request({
            url:'/byzCorp/user/getUser.ajax',
            params : {
                data: Ext.encode({
                    userName: Ext.getCmp('txtUserName').getValue(),
                    password : Ext.getCmp('txtPassword').getValue()
                }),
            },
            success : function(response){
            var jsonData = Ext.util.JSON.decode(response.responseText.trim());
            if (jsonData.success) {
                Ext.getCmp('loginWindow').destroy();
                //Ext.getCmp('lblUserName').setValue(jsonData.data.firstName+' '+jsonData.data.lastName+'<br>'+'Yazılım Uzmanı');                    Ext.getCmp('userId').setValue(jsonData.data.userId);
                }else{
                    scope.showErrorMessage(jsonData.message);
                }
            },
            failure: function (response) {
                var jsonData = Ext.util.JSON.decode(response.responseText.trim());
                scope.showErrorMessage(jsonData.message);
            }
        });
    }

});
