/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'lookUpDetails',
        'lookUps',
        'userDetail',
        'userLeave'
    ],
    stores: [
        'lookUps',
        'lookUpDetails',
        'ludStatus',
        'userDetail',
        'userLeave',
        'ludDepartment',
        'ludBranch',
        'ludWorkType',
        'ludTitle',
        'ludCitizen',
        'ludGender',
        'ludBloodType',
        'ludMaritialStatus',
        'ludDriverClass',
        'ludProvince',
        'ludCountry',
        'ludRelationShip',
        'ludDisabled',
        'ludAccountId',
        'ludBank',
        'ludBankBranch',
        'ludRole',
        'ludYear',
        'ludLeaveRecordType',
        'ludLeaveType',
        'ludReportType'
    ],
    views: [
        'menuPanel',
        'viewport',
        'financeManagement',
        'lookUpManagement',
        'otelManagement',
        'stockManagement',
        'hrManagement',
        'loginWindow',
        'generalPagingToolbar'
    ],
    controllers: [
        'BaseController',
        'MenuController',
        'LoginController',
        'LookUpController',
        'HrController'
    ],
    name: 'byzCorp',
    title: 'byzCorp',

    launch: function() {
        Ext.create('byzCorp.view.viewport');
        var winLogin = Ext.create('byzCorp.view.loginWindow',{
                    title: 'Giriş Ekranı',
                    xtype:'panel',
                    closable: false,
                });
                winLogin.show();
    }

});
