/*
 * File: app/view/generalPagingToolbar.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.generalPagingToolbar', {
    extend: 'Ext.toolbar.Paging',
    alias: 'widget.generalPagingToolbar',

    requires: [
        'byzCorp.view.generalPagingToolbarViewModel'
    ],

    viewModel: {
        type: 'generalpagingtoolbar'
    },
    width: 998,
    afterPageText: '/ {0}',
    beforePageText: 'Sayfa',
    displayInfo: true,
    displayMsg: 'Görüntülenen {0} - {1} of {2}',
    emptyMsg: 'Görüntülenecek kayıt bulunamadı..',
    firstText: 'İlk Sayfa',
    lastText: 'Son Sayfa',
    nextText: 'Sonraki Sayfa',
    prevText: 'Önceki Sayfa',
    refreshText: 'Yenile'

});