/*
 * File: app/view/hrSaveOrUpdate.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.hrSaveOrUpdate', {
    extend: 'Ext.window.Window',
    alias: 'widget.hrSaveOrUpdate',

    requires: [
        'byzCorp.view.hrSaveOrUpdateViewModel',
        'byzCorp.view.generalPagingToolbar',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.field.File',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.grid.Panel',
        'Ext.grid.column.Check',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'hrsaveorupdate'
    },
    modal: true,
    height: 855,
    id: 'hrSaveOrUpdate',
    width: 1289,
    layout: 'border',
    title: 'addEmployee',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 212,
            layout: 'border',
            header: false,
            items: [
                {
                    xtype: 'form',
                    region: 'east',
                    width: 181,
                    bodyPadding: 3,
                    header: false,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 152,
                            id: 'employeeImage',
                            margin: 8,
                            style: '\'border: 0px;border-radius: 100px;',
                            width: 160,
                            src: 'resources/images/1.png'
                        },
                        {
                            xtype: 'filefield',
                            height: 30,
                            id: 'addEmployeeImage',
                            margin: '0 0 3 0',
                            buttonText: 'Ekle..'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'west',
                    id: 'employeeSubInfoWest',
                    width: 337,
                    bodyPadding: 3,
                    header: false,
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'managerId',
                            fieldLabel: 'Yönetici'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            hidden: true,
                            id: 'userId',
                            fieldLabel: 'userId'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'branchId',
                            fieldLabel: 'Şube',
                            autoHideInputMask: false,
                            anyMatch: true,
                            autoLoadOnValue: true,
                            displayField: 'name',
                            minChars: 0,
                            store: 'ludBranch',
                            valueField: 'value'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'departmentId',
                            width: 150,
                            fieldLabel: 'Departman',
                            blankText: 'Zorunlu alan',
                            anyMatch: true,
                            autoLoadOnValue: true,
                            displayField: 'name',
                            minChars: 0,
                            store: 'ludDepartment',
                            valueField: 'value'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'titleId',
                            fieldLabel: 'Ünvanı',
                            anyMatch: true,
                            autoLoadOnValue: true,
                            displayField: 'name',
                            minChars: 0,
                            store: 'ludTitle',
                            valueField: 'value'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'workTypeId',
                            fieldLabel: 'Çalışma Şekli',
                            anyMatch: true,
                            autoLoadOnValue: true,
                            displayField: 'name',
                            minChars: 0,
                            store: 'ludWorkType',
                            valueField: 'value'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'west',
                    id: 'employeeSubInfoCenter',
                    width: 403,
                    bodyPadding: 3,
                    header: false,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'identityNo',
                            fieldLabel: 'T.C. Kimlik No'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'firstName',
                            fieldLabel: 'Adı'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'lastName',
                            fieldLabel: 'Soyadı'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'email',
                            fieldLabel: 'E-Posta',
                            inputType: 'email'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'roleId',
                            fieldLabel: 'Yetki Türü',
                            displayField: 'name',
                            store: 'ludRole',
                            valueField: 'value'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'employeeSubInfoEast',
                    bodyPadding: 3,
                    header: false,
                    items: [
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            id: 'startWorkDate',
                            fieldLabel: 'İşe Başlama Tarihi',
                            labelWidth: 110,
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            id: 'insuranceDate',
                            fieldLabel: 'İlk Sigorta Tarihi',
                            labelWidth: 110,
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'citizenId',
                            fieldLabel: 'Uyruğu',
                            labelWidth: 110,
                            anyMatch: true,
                            autoLoadOnValue: true,
                            displayField: 'name',
                            minChars: 0,
                            store: 'ludCitizen',
                            valueField: 'value'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'genderId',
                            fieldLabel: 'Cinsiyeti',
                            labelWidth: 110,
                            anyMatch: true,
                            autoLoadOnValue: true,
                            displayField: 'name',
                            minChars: 0,
                            store: 'ludGender',
                            valueField: 'value'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'boodTypeId',
                            fieldLabel: 'Kan Grubu',
                            labelWidth: 110,
                            anyMatch: true,
                            autoLoadOnValue: true,
                            displayField: 'name',
                            minChars: 0,
                            store: 'ludBloodType',
                            valueField: 'value'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            id: 'employeeTabPanel',
            itemId: 'employeeTabPanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    id: 'employeeInfo',
                    layout: 'border',
                    title: 'Kişisel Bilgiler',
                    items: [
                        {
                            xtype: 'form',
                            region: 'west',
                            id: 'employeeInfoWest',
                            margin: '3 3 0 3',
                            width: 373,
                            bodyPadding: 3,
                            header: false,
                            title: 'Kimlik/Ehliyet Bilgileri',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'maritialStatusId',
                                    fieldLabel: 'Medeni Hali',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludMaritialStatus',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    id: 'childCount',
                                    fieldLabel: 'Çocuk Sayısı'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'birthPlace',
                                    fieldLabel: 'Doğum Yeri'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'birthDate',
                                    fieldLabel: 'Doğum Tarihi',
                                    format: 'd/m/Y'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'motherName',
                                    fieldLabel: 'Anne adı'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'fatherName',
                                    fieldLabel: 'Baba Adı'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'classId',
                                    fieldLabel: 'Ehliyet Sınıfı',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludDriverClass',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'licenceNo',
                                    fieldLabel: 'Belge No'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'issuedDate',
                                    fieldLabel: 'Veriliş Tarihi',
                                    format: 'd/m/Y'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'issuedProvinceId',
                                    fieldLabel: 'Verildiği İl',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludProvince',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'issuedCountryId',
                                    fieldLabel: 'Verildiği İlçe',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludCountry',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'disabledId',
                                    fieldLabel: 'Engel Derecesi',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludDisabled',
                                    valueField: 'value'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'west',
                            id: 'employeeInfoCenter',
                            margin: '3 3 0 0',
                            width: 417,
                            bodyPadding: 3,
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'countryId',
                                    fieldLabel: 'Adres İl',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludProvince',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'provinceId',
                                    fieldLabel: 'Adres İlçe',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludCountry',
                                    transform: 'countryId',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'village',
                                    fieldLabel: 'Mahalle/Köy'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'zipCode',
                                    fieldLabel: 'Posta Kodu'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    id: 'addressDescription',
                                    fieldLabel: 'Adres Detay'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'mobilePhone',
                                    fieldLabel: 'Cep Telefonu'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'homePhone',
                                    fieldLabel: 'Ev Telefonu'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'emergencyPerson',
                                    fieldLabel: 'Acil Durum Kişi'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'relationShipId',
                                    fieldLabel: 'Yakınlığı',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludRelationShip',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'emergencyPhoneFirst',
                                    fieldLabel: 'Acil Kişi Tel. 1'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'emergencyPhoneSecond',
                                    fieldLabel: 'Acil Kişi Tel. 2'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'center',
                            id: 'employeeInfoEast',
                            margin: '3 3 0 0',
                            bodyPadding: 3,
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'accountTypeId',
                                    fieldLabel: 'Hesap Tipi',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludAccountId',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'bankId',
                                    fieldLabel: 'Banka Adı',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludBank',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'bankBranchId',
                                    fieldLabel: 'Şube Adı',
                                    anyMatch: true,
                                    autoLoadOnValue: true,
                                    minChars: 0
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'bankBranchCode',
                                    fieldLabel: 'Şube Kodu'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'accountNo',
                                    fieldLabel: 'Hesap No'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'iban',
                                    fieldLabel: 'IBAN'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    id: 'bankDescription',
                                    fieldLabel: 'Banka Açıklama'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'employeeLeave',
                    layout: 'border',
                    title: 'İzin/Rapor Bilgileri',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'employeeLeaveGrid',
                            title: 'İzin/Rapor Listesi',
                            forceFit: true,
                            store: 'userLeave',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 119,
                                    dataIndex: 'userLeaveId',
                                    text: 'userLeaveId'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 119,
                                    dataIndex: 'userId',
                                    text: 'userId'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 119,
                                    dataIndex: 'recordTypeId',
                                    text: 'Türü'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 83,
                                    dataIndex: 'recordTypeName',
                                    text: 'Türü'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'leaveTypeId',
                                    text: 'Tipi'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'reportTypeId',
                                    text: 'Tipi'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'typeName',
                                    text: 'Tipi'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 142,
                                    dataIndex: 'startDate',
                                    text: 'Başlama Zamanı'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 142,
                                    dataIndex: 'endDate',
                                    text: 'Bitiş Zamanı'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 142,
                                    dataIndex: 'leaveStartWorkDate',
                                    text: 'Dönüş Zamanı'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'time',
                                    text: 'Süre'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'leaveYear',
                                    text: 'Yılı'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'leaveStatus',
                                    text: 'Kalan'
                                },
                                {
                                    xtype: 'checkcolumn',
                                    dataIndex: 'leaveStatus',
                                    text: 'Statü'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'generalPagingToolbar',
                                    dock: 'bottom'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'north',
                            height: 32,
                            id: 'hrGridSearch1',
                            margin: '3 0 3 0',
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'textfield',
                                    region: 'center',
                                    id: 'searchHrGrid1',
                                    emptyText: 'Ara..',
                                    enableKeyEvents: true
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'west',
                            split: true,
                            id: 'leaveSaveOrUpdateForm',
                            width: 339,
                            bodyPadding: 3,
                            collapsible: true,
                            title: 'İzin/Rapor Kayıt',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'recordTypeId',
                                    fieldLabel: 'Kayıt Türü',
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludLeaveRecordType',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    hidden: true,
                                    id: 'leaveTypeId',
                                    fieldLabel: 'İzin Tipi',
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludLeaveType',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    hidden: true,
                                    id: 'leaveYear',
                                    fieldLabel: 'Kullanılan Yıl',
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludYear',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    hidden: true,
                                    id: 'reportTypeId',
                                    fieldLabel: 'Rapor Tipi',
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludReportType',
                                    valueField: 'value'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'startDate',
                                    fieldLabel: 'Başlangıç Tarihi',
                                    format: 'd/m/Y'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    id: 'time',
                                    fieldLabel: 'Süre'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'endDate',
                                    fieldLabel: 'Bitiş Tarihi',
                                    format: 'd/m/Y'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'leaveStartWorkDate',
                                    fieldLabel: 'Dönüş Tarihi',
                                    format: 'd/m/Y'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'leaveStatus',
                                    fieldLabel: 'Statü',
                                    autoLoadOnValue: true,
                                    displayField: 'name',
                                    minChars: 0,
                                    store: 'ludStatus',
                                    valueField: 'value'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'east',
                            split: false,
                            id: 'permissionRightGrid',
                            width: 409,
                            collapsed: false,
                            collapsible: true,
                            title: 'İzin Hakları',
                            split: true,
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    width: 99,
                                    dataIndex: 'date',
                                    text: 'Yıl'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    width: 207,
                                    text: 'İzin Hakkı'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 207,
                                    dataIndex: 'string',
                                    text: 'Kalan İzin'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Statü'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'form',
                                    dock: 'top',
                                    height: 32,
                                    id: 'hrGridSearch6',
                                    margin: '3 0 3 0',
                                    width: 100,
                                    layout: 'border',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            region: 'center',
                                            id: 'searchHrGrid6',
                                            margin: '0 3 0 0',
                                            labelWidth: 60,
                                            emptyText: 'İzin Hakkı',
                                            enableKeyEvents: true
                                        },
                                        {
                                            xtype: 'combobox',
                                            region: 'west',
                                            margin: '0 3 0 0',
                                            width: 92,
                                            labelWidth: 50,
                                            emptyText: 'İzin Yılı',
                                            autoLoadOnValue: true,
                                            displayField: 'name',
                                            minChars: 0,
                                            store: 'ludYear',
                                            valueField: 'value'
                                        },
                                        {
                                            xtype: 'button',
                                            region: 'east',
                                            margin: '0 3 0 0',
                                            width: 60,
                                            text: 'Ekle'
                                        },
                                        {
                                            xtype: 'button',
                                            region: 'east',
                                            ui: 'dashboardWarningRed-small',
                                            width: 60,
                                            text: 'Sil'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'employeePayment',
                    layout: 'border',
                    title: 'Ödeme Bilgileri',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'employeePaymentGrid',
                            title: 'Ödeme Listesi',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 119,
                                    dataIndex: 'string',
                                    text: 'Ödeme Türü'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 142,
                                    dataIndex: 'date',
                                    text: 'Ödeme Tarihi'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 150,
                                    dataIndex: 'bool',
                                    text: 'Ödenen Tutar'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 154,
                                    dataIndex: 'bool',
                                    text: 'Mahsup Durumu'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'north',
                            height: 32,
                            id: 'hrGridSearch2',
                            margin: '3 0 3 0',
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'textfield',
                                    region: 'center',
                                    id: 'searchHrGrid2',
                                    emptyText: 'Ara..',
                                    enableKeyEvents: true
                                },
                                {
                                    xtype: 'button',
                                    region: 'west',
                                    itemId: 'btnHrSaveOrUpdate1',
                                    margin: '0 2 0 0',
                                    maxWidth: 150,
                                    minWidth: 150,
                                    ui: 'dashboardWarningMagenta-small',
                                    width: 150,
                                    iconCls: 'fa fa-plus-square',
                                    text: 'İzin Hakları'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'west',
                            split: true,
                            width: 294,
                            bodyPadding: 3,
                            collapsible: true,
                            title: 'Ödeme Kayıt',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Türü'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'izinse izin tipi'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'izinse izin yili'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'rapor raportipi'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Başlangıç Tarihi'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Süre'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Bitiş Tarihi'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'employeeSalary',
                    layout: 'border',
                    title: 'Maaş Bilgileri',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'employeeSalaryGrid',
                            title: 'Maaş Listesi',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 119,
                                    dataIndex: 'string',
                                    text: 'Ödeme Türü'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 142,
                                    dataIndex: 'date',
                                    text: 'Ödeme Tarihi'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 150,
                                    dataIndex: 'bool',
                                    text: 'Ödenen Tutar'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 154,
                                    dataIndex: 'bool',
                                    text: 'Mahsup Durumu'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'north',
                            height: 32,
                            id: 'hrGridSearch3',
                            margin: '3 0 3 0',
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'textfield',
                                    region: 'center',
                                    id: 'searchHrGrid3',
                                    emptyText: 'Ara..',
                                    enableKeyEvents: true
                                },
                                {
                                    xtype: 'button',
                                    region: 'west',
                                    itemId: 'btnHrSaveOrUpdate1',
                                    margin: '0 2 0 0',
                                    maxWidth: 150,
                                    minWidth: 150,
                                    ui: 'dashboardWarningMagenta-small',
                                    width: 150,
                                    iconCls: 'fa fa-plus-square',
                                    text: 'İzin Hakları'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'west',
                            split: true,
                            width: 294,
                            bodyPadding: 3,
                            collapsible: true,
                            title: 'Maaş Kayıt',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Türü'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'izinse izin tipi'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'izinse izin yili'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'rapor raportipi'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Başlangıç Tarihi'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Süre'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Bitiş Tarihi'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'employeeDebt',
                    layout: 'border',
                    title: 'Zimmet Bilgileri',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'employeeDebtGrid',
                            title: 'Zimmet Listesi',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 119,
                                    dataIndex: 'string',
                                    text: 'Ödeme Türü'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 142,
                                    dataIndex: 'date',
                                    text: 'Ödeme Tarihi'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 150,
                                    dataIndex: 'bool',
                                    text: 'Ödenen Tutar'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 154,
                                    dataIndex: 'bool',
                                    text: 'Mahsup Durumu'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'north',
                            height: 32,
                            id: 'hrGridSearch4',
                            margin: '3 0 3 0',
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'textfield',
                                    region: 'center',
                                    id: 'searchHrGrid4',
                                    emptyText: 'Ara..',
                                    enableKeyEvents: true
                                },
                                {
                                    xtype: 'button',
                                    region: 'west',
                                    itemId: 'btnHrSaveOrUpdate1',
                                    margin: '0 2 0 0',
                                    maxWidth: 150,
                                    minWidth: 150,
                                    ui: 'dashboardWarningMagenta-small',
                                    width: 150,
                                    iconCls: 'fa fa-plus-square',
                                    text: 'İzin Hakları'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'west',
                            split: true,
                            width: 294,
                            bodyPadding: 3,
                            collapsible: true,
                            title: 'Zimmet Kayıt',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Türü'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'izinse izin tipi'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'izinse izin yili'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'rapor raportipi'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Başlangıç Tarihi'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Süre'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Bitiş Tarihi'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'employeeEducation',
                    layout: 'border',
                    title: 'Eğitim/Sertifika Bilgileri',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'employeeEducationGrid',
                            title: 'Eğitim/Sertifika Listesi',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 119,
                                    dataIndex: 'string',
                                    text: 'Ödeme Türü'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 142,
                                    dataIndex: 'date',
                                    text: 'Ödeme Tarihi'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 150,
                                    dataIndex: 'bool',
                                    text: 'Ödenen Tutar'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 154,
                                    dataIndex: 'bool',
                                    text: 'Mahsup Durumu'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'north',
                            height: 32,
                            id: 'hrGridSearch5',
                            margin: '3 0 3 0',
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'textfield',
                                    region: 'center',
                                    id: 'searchHrGrid5',
                                    emptyText: 'Ara..',
                                    enableKeyEvents: true
                                },
                                {
                                    xtype: 'button',
                                    region: 'west',
                                    itemId: 'btnHrSaveOrUpdate1',
                                    margin: '0 2 0 0',
                                    maxWidth: 150,
                                    minWidth: 150,
                                    ui: 'dashboardWarningMagenta-small',
                                    width: 150,
                                    iconCls: 'fa fa-plus-square',
                                    text: 'İzin Hakları'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            region: 'west',
                            split: true,
                            width: 294,
                            bodyPadding: 3,
                            collapsible: true,
                            title: 'Eğitim/Sertifika Kayıt',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Türü'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'izinse izin tipi'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'izinse izin yili'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'rapor raportipi'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Başlangıç Tarihi'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Süre'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Bitiş Tarihi'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'form',
            region: 'south',
            height: 34,
            id: 'hrGridButtonForm1',
            margin: 3,
            layout: 'border',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'button',
                    dock: 'left',
                    itemId: 'btnHrSaveOrUpdate',
                    margin: '0 2 0 0',
                    maxWidth: 150,
                    minWidth: 150,
                    iconCls: 'fa fa-plus-square',
                    text: 'Kaydet'
                },
                {
                    xtype: 'button',
                    dock: 'left',
                    maxWidth: 150,
                    minWidth: 150,
                    ui: 'dashboardWarningRed-small',
                    iconCls: 'fa fa-minus-square',
                    text: 'Sil'
                },
                {
                    xtype: 'button',
                    margins: '0 2 0 0',
                    dock: 'right',
                    maxWidth: 150,
                    minWidth: 150,
                    ui: 'dashboardWarningMagenta-small',
                    iconCls: 'fa fa-print',
                    text: 'Yazdır',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                iconCls: 'fa fa-info',
                                text: 'Personel Kartı'
                            },
                            {
                                xtype: 'menuitem',
                                iconCls: 'fa fa-list-ol',
                                text: 'Personel Listesi'
                            }
                        ]
                    }
                }
            ]
        }
    ]

});