/*
 * File: app/view/loginWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.loginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginWindow',

    requires: [
        'byzCorp.view.loginWindowViewModel',
        'Ext.container.Container',
        'Ext.button.Button',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'loginwindow'
    },
    border: false,
    id: 'loginWindow',
    resizable: false,
    width: 917,
    defaultFocus: 'txtUserName',
    bodyStyle: 'background-image:url(resources/images/loginBackGround.jpg) !important;',
    closable: false,
    frameHeader: false,
    header: false,
    maximized: true,

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            width: 313,
            layout: {
                type: 'vbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    disabled: true,
                    dock: 'top',
                    margin: '0 0 150 0',
                    iconAlign: 'top',
                    iconCls: 'x-fa fa-home',
                    text: '<b><font size="6" color="white"><br>byzCorp Finance </b></font></br>'
                },
                {
                    xtype: 'textfield',
                    dock: 'top',
                    id: 'txtUserName',
                    margin: '2 0 0 0',
                    emptyText: 'Kullanıcı Adı.'
                },
                {
                    xtype: 'textfield',
                    dock: 'top',
                    id: 'txtPassword',
                    margin: '2 0 0 0',
                    inputType: 'password',
                    emptyText: 'Şifre....'
                },
                {
                    xtype: 'button',
                    dock: 'top',
                    id: 'btnLogin',
                    margin: '50 0 0 0',
                    iconCls: 'fa fa-sign-in',
                    text: 'Giriş'
                },
                {
                    xtype: 'button',
                    dock: 'top',
                    margin: '2 0 0 0',
                    width: 150,
                    iconCls: 'fa fa-question-circle',
                    text: 'Şifremi Unuttum'
                }
            ]
        }
    ]

});