/*
 * File: app/view/lookUpManagement.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.lookUpManagement', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.lookUpManagement',

    requires: [
        'byzCorp.view.lookUpManagementViewModel',
        'byzCorp.view.generalPagingToolbar',
        'Ext.grid.Panel',
        'Ext.grid.column.Check',
        'Ext.view.Table',
        'Ext.form.Panel',
        'Ext.toolbar.Paging',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'lookupmanagement'
    },
    height: 765,
    width: 1009,
    layout: 'border',
    title: 'LookUp Management',

    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            id: 'lookUpGrid',
            margin: '2 2 0 2',
            autoLoad: true,
            store: 'lookUps',
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 4,
                    hidden: true,
                    dataIndex: 'lookUpId',
                    text: 'lookUpId'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 4,
                    dataIndex: 'name',
                    text: 'Açıklama'
                },
                {
                    xtype: 'checkcolumn',
                    flex: 1,
                    dataIndex: 'status',
                    text: 'Statü'
                }
            ],
            viewConfig: {
                id: 'lookUpGridTable'
            },
            dockedItems: [
                {
                    xtype: 'form',
                    dock: 'top',
                    height: 37,
                    id: 'lookUpGridSearch',
                    width: 325,
                    layout: 'border',
                    bodyPadding: 10,
                    dockedItems: [
                        {
                            xtype: 'textfield',
                            dock: 'top',
                            id: 'searchLookUpGrid',
                            margin: '2 0 0 0',
                            emptyText: 'Ara..',
                            enableKeyEvents: true
                        }
                    ]
                },
                {
                    xtype: 'generalPagingToolbar',
                    dock: 'bottom'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            region: 'south',
            split: true,
            height: 304,
            id: 'lookUpDetailGrid',
            margin: '0 2 0 2',
            collapsible: true,
            iconCls: 'fa fa-list-ol',
            title: 'Tanım Detayları',
            store: 'lookUpDetails',
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 3,
                    hidden: true,
                    width: 210,
                    dataIndex: 'lookUpDetailId',
                    text: 'Açıklama'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 3,
                    width: 210,
                    dataIndex: 'name',
                    text: 'Açıklama'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'value',
                    text: 'Değer'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'orderNo',
                    text: 'Sıra No'
                },
                {
                    xtype: 'checkcolumn',
                    flex: 1,
                    dataIndex: 'status',
                    text: 'Statü'
                }
            ],
            viewConfig: {
                id: 'lookUpDetailGridTable'
            },
            dockedItems: [
                {
                    xtype: 'form',
                    dock: 'left',
                    height: 37,
                    id: 'lookUpDetailGridAdd',
                    width: 302,
                    layout: 'form',
                    bodyPadding: '',
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'lookUpDetailId',
                            fieldLabel: 'LookUpDetailId'
                        },
                        {
                            xtype: 'textfield',
                            id: 'name',
                            fieldLabel: 'Açıklama',
                            allowBlank: false,
                            blankText: 'Zorunlu Alan'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'value',
                            fieldLabel: 'Değer',
                            allowBlank: false,
                            blankText: 'Zorunlu alan'
                        },
                        {
                            xtype: 'numberfield',
                            id: 'orderNo',
                            fieldLabel: 'Sıra No',
                            allowBlank: false,
                            blankText: 'Zorunlu alan'
                        },
                        {
                            xtype: 'combobox',
                            id: 'status',
                            fieldLabel: 'Statü',
                            allowBlank: false,
                            blankText: 'Zorunlu alan',
                            anyMatch: true,
                            autoLoadOnValue: true,
                            displayField: 'name',
                            minChars: 0,
                            store: 'ludStatus',
                            valueField: 'value'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'panel',
                            dock: 'bottom',
                            height: 35,
                            layout: 'border',
                            dockedItems: [
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    dock: 'left',
                                    itemId: 'bntLookUpDetailSaveOrUpdate',
                                    margin: '0 2 0 0',
                                    maxWidth: 150,
                                    minWidth: 150,
                                    iconCls: 'fa fa-plus-square',
                                    text: 'Ekle/Düzelt'
                                }
                            ],
                            items: [
                                {
                                    xtype: 'button',
                                    region: 'west',
                                    id: 'btnLookUpDetailRemove',
                                    maxWidth: 150,
                                    minWidth: 150,
                                    ui: 'dashboardWarningRed-small',
                                    width: 150,
                                    iconCls: 'fa fa-minus-square',
                                    text: 'Sil'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'generalPagingToolbar',
                    dock: 'bottom'
                }
            ]
        }
    ]

});