/*
 * File: app/view/menuPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('byzCorp.view.menuPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.menuPanel',

    requires: [
        'byzCorp.view.menuPanelViewModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'menupanel'
    },
    height: 529,
    width: 208,
    layout: 'form',
    iconCls: 'fa fa-bars',
    title: 'Menü',

    dockedItems: [
        {
            xtype: 'button',
            dock: 'top',
            itemId: 'menuBtnFinanceManagement',
            margin: '2 0 0 0',
            iconAlign: 'top',
            iconCls: 'fa fa-money',
            text: 'Finans Yönetimi',
            textAlign: 'left'
        },
        {
            xtype: 'button',
            dock: 'top',
            itemId: 'menuBtnStockManagement',
            margin: '2 0 0 0',
            iconAlign: 'top',
            iconCls: 'fa fa-cubes',
            text: 'Stok Yönetimi',
            textAlign: 'left'
        },
        {
            xtype: 'button',
            dock: 'top',
            itemId: 'menuBtnHrManagement',
            margin: '2 0 0 0',
            iconAlign: 'top',
            iconCls: 'fa fa-users',
            text: 'İnsan Kaynakları Yönetimi',
            textAlign: 'left'
        },
        {
            xtype: 'button',
            dock: 'top',
            itemId: 'menuBtnOtelManagement',
            margin: '2 0 0 0',
            iconAlign: 'top',
            iconCls: 'fa fa-h-square',
            text: 'Otel Yönetimi',
            textAlign: 'left'
        },
        {
            xtype: 'button',
            dock: 'top',
            itemId: 'menuBtnLookUpManagement',
            margin: '2 0 0 0',
            iconAlign: 'top',
            iconCls: 'fa fa-puzzle-piece',
            text: 'Tanımlama Yönetimi',
            textAlign: 'left'
        }
    ]

});