/* auto generated by architect */ 
Ext.theme.addManifest([
    {
        "ui": "dashboardWarningRed",
        "xtype": "button"
    },
    {
        "ui": "dashboardWarningYellow",
        "xtype": "button"
    },
    {
        "ui": "dashboardWarningGreen",
        "xtype": "button"
    },
    {
        "ui": "dashboardWarningMagenta",
        "xtype": "button"
    }
]);